# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    git config --global user.email "vjpking5913@gmail.com"
    git config --global user.name "Ngu Mai"
    npm install
    npm run build
    npm run deploy
  displayName: 'npm install and build'
