# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
    git config --global user.email "vjpking5913@gmail.com"
    git config --global user.name "Ngu Mai"
    git remote set-url origin git@github.com:maihongngu/cv
    npm run deploy -- -r https://$(username):$(password)@github.com/maihongngu/cv.git
  displayName: 'npm install and build'
